# Generated by Django 3.1.7 on 2021-04-02 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_relationship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'verbose_name': 'Отношение', 'verbose_name_plural': 'Отношения'},
        ),
    ]
